#!/usr/bin/env bash
# Idempotent repository bootstrap for the deau Cloud Agent environment.
# Runs after the repository is checked out. Prepares a local PostgreSQL
# instance, installs Node dependencies, syncs the Prisma schema and seeds
# sample data. Safe to re-run.
set -euo pipefail

PG_VERSION=16
PG_CLUSTER=main
DB_NAME=deau
DB_USER=deau
DB_PASSWORD=deau

echo "==> Ensuring PostgreSQL ${PG_VERSION} is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    "postgresql-${PG_VERSION}" postgresql-contrib
fi

echo "==> Ensuring PostgreSQL cluster is running"
if ! sudo pg_lsclusters -h 2>/dev/null | awk '{print $4}' | grep -q online; then
  sudo pg_ctlcluster "${PG_VERSION}" "${PG_CLUSTER}" start || true
fi

# Wait for the server to accept connections.
for _ in $(seq 1 30); do
  if pg_isready -h localhost -p 5432 >/dev/null 2>&1; then break; fi
  sleep 1
done

echo "==> Ensuring role and database exist"
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}' CREATEDB;"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"

echo "==> Ensuring local .env exists"
if [ ! -f .env ]; then
  cat > .env <<'EOF'
# Local Cloud Agent development environment (auto-generated by env setup).
# Local PostgreSQL provisioned in the VM. Prisma connects via DATABASE_URL.
DATABASE_URL="postgresql://deau:deau@localhost:5432/deau?schema=public"

# Batch/cron secrets for POST/GET /api/matches/run (x-batch-secret / bearer).
MATCH_BATCH_SECRET="local-dev-match-batch-secret"
CRON_SECRET="local-dev-match-batch-secret"

# Supabase is only required for real end-user auth (magic link / OAuth) and the
# authenticated APIs. These placeholders let the app build and render locally.
# Replace with real Supabase project values (via Secrets) to exercise auth flows.
NEXT_PUBLIC_SUPABASE_URL="https://placeholder.supabase.co"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY="sb_publishable_placeholder"
EOF
fi

echo "==> Installing Node dependencies"
npm ci

echo "==> Generating Prisma client"
npx prisma generate

echo "==> Syncing database schema"
npx prisma db push --skip-generate

echo "==> Seeding sample data"
npm run db:seed

echo "==> Install complete"
